/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTelegramRouteImport } from './routes/_authenticated/telegram'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTelegramRoute = AuthenticatedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/telegram': typeof AuthenticatedTelegramRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/telegram': typeof AuthenticatedTelegramRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/chat'
    | '/dashboard'
    | '/developer'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/memory'
    | '/progress'
    | '/settings'
    | '/tasks'
    | '/telegram'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/dashboard'
    | '/developer'
    | '/goals'
    | '/habits'
    | '/journal'
    | '/memory'
    | '/progress'
    | '/settings'
    | '/tasks'
    | '/telegram'
    | '/api/chat'
    | '/chat/$threadId'
    | '/chat'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/journal'
    | '/_authenticated/memory'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/telegram'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/chat/'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/telegram': {
      id: '/_authenticated/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AuthenticatedTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTelegramRoute: typeof AuthenticatedTelegramRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTelegramRoute: AuthenticatedTelegramRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
